### ISSUE TITLE
Error build

### ISSUE THREAD

**Issue by ghost** [doanbaanh/docker-goip-sms-server#1]
W: GPG error: http://archive.debian.org wheezy Release: The following signatures were invalid: KEYEXPIRED 1587841717 KEYEXPIRED 1668891673 KEYEXPIRED 1557241909
W: GPG error: http://archive.debian.org wheezy/updates Release: The following signatures were invalid: KEYEXPIRED 1668892417 KEYEXPIRED 1587841717

**Comment by doanbaanh** [comment]
@ghost Sorry for long time answer. Build updated.
